receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

# 在这里分别定义两个处理器的配置
processors:
  batch:
  attributesfilter:
    drop:
      - key: "attr1"
        value: "value1"

exporters:
  debug:
  otlp:
    endpoint: jaeger:4317

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributesfilter]
      exporters: [debug]