// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("attributesfilter")
	ScopeName = "github.com/prchen818/opentelemetry-collector-contrib/processor/attributesfilterprocessor"
)

const (
	TracesStability  = component.StabilityLevelBeta
)
